import 'package:galaxy_planets/models/planets_des_model.dart';

class Data {
  static List<PlanetsDesModel> planetsList = [
    PlanetsDesModel(
        name: "Mercury",
        description:
            "Mercury is the closest planet to the Sun and due to its proximity it is not easily seen except during twilight. For every two orbits of the Sun, Mercury completes three rotations about its axis and up until 1965 it was thought that the same side of Mercury constantly faced the Sun. Thirteen times a century Mercury can be observed from the Earth passing across the face of the Sun in an event called a transit, the next will occur on the 9th May 2016.",
        position: "1",
        image: "assets/planets/mercury.png",
        velocity: "47",
        distance: "58",
        average_orbital_speed: "47.36 km/s",
        satellite: "0",
        surface_area: "74,797,000 km2",
        rotation_period: "59 Earth days",
        temperature: "333°F"),
    PlanetsDesModel(
        name: "Venus",
        description:
            "Venus is the second planet from the Sun and is the second brightest object in the night sky after the Moon. Named after the Roman goddess of love and beauty, Venus is the second largest terrestrial planet and is sometimes referred to as the Earth’s sister planet due the their similar size and mass. The surface of the planet is obscured by an opaque layer of clouds made up of sulphuric acid.",
        position: "2",
        image: "assets/planets/venus.png",
        velocity: "35",
        distance: "180",
        average_orbital_speed: "35 km/s (78,000 mph)",
        satellite: "0",
        surface_area: "460.2 million km²",
        rotation_period: "243d 0h 0m (243 Earth days )",
        temperature: "867°F"),
    PlanetsDesModel(
        name: "Earth",
        position: "3",
        description:"Earth is the third planet from the Sun and is the largest of the terrestrial planets. The Earth is the only planet in our solar system not to be named after a Greek or Roman deity. The Earth was formed approximately 4.54 billion years ago and is the only known planet to support life.",
        image: "assets/planets/earth.png",
        velocity: "29",
        distance: "149",
        average_orbital_speed: "29.8 km/s (18.5 mi/s)",
        satellite: "8,261",
        surface_area: "510.1 million km²",
        rotation_period: " 23 hours 56 minutes and 4 seconds",
        temperature: "59°F"),
    PlanetsDesModel(
        name: "Mars",
        position: "4",
        description:"Mars is the fourth planet from the Sun and is the second smallest planet in the solar system. Named after the Roman god of war, Mars is also often described as the “Red Planet” due to its reddish appearance. Mars is a terrestrial planet with a thin atmosphere composed primarily of carbon dioxide.",
        image: "assets/planets/mars.png",
        velocity: "24",
        distance: "227",
        average_orbital_speed: "53,979 miles per hour",
        satellite: "2",
        surface_area: "144.4 million km²",
        rotation_period: "24.6 hours",
        temperature: "-85°F"),
    PlanetsDesModel(
        name: "Jupiter",
        position: "5",
        description:"Mars is the fourth planet from the Sun and is the second smallest planet in the solar system. Named after the Roman god of war, Mars is also often described as the “Red Planet” due to its reddish appearance. Mars is a terrestrial planet with a thin atmosphere composed primarily of carbon dioxide.",
        image: "assets/planets/jupiter.png",
        velocity: "13",
        distance: "778",
        average_orbital_speed: "29,236 miles per hour",
        satellite: "95 moons",
        surface_area: "61.42 billion km²",
        rotation_period: "4,333 Earth days",
        temperature: "-166°F"),
    PlanetsDesModel(
        name: "Saturn",
        position: "6",
        description:"Saturn is the sixth planet from the Sun and the most distant that can be seen with the naked eye. Saturn is the second largest planet and is best known for its fabulous ring system that was first observed in 1610 by the astronomer Galileo Galilei. Like Jupiter, Saturn is a gas giant and is composed of similar gasses including hydrogen, helium and methane.",
        image: "assets/planets/saturn.png",
        velocity: "9",
        distance: "1426",
        average_orbital_speed: "9.68 km/s",
        satellite: "146 moons",
        surface_area: "42.7 billion km²",
        rotation_period: "0d 10h 34m",
        temperature: "-178"),
    PlanetsDesModel(
        name: "Uranus",
        position: "7",
        description:"Uranus is the seventh planet from the Sun. While being visible to the naked eye, it was not recognised as a planet due to its dimness and slow orbit. Uranus became the first planet discovered with the use of a telescope. Uranus is tipped over on its side with an axial tilt of 98 degrees. It is often described as “rolling around the Sun on its side.",
        image: "assets/planets/uranus.png",
        velocity: "6",
        distance: "2870",
        average_orbital_speed: "15,290 miles per hour",
        satellite: "28 known moons",
        surface_area: "8.083 billion km²",
        rotation_period: "0d 17h 14m",
        temperature: "-320°F"),
    PlanetsDesModel(
        name: "Neptune",
        position: "8",
        description:"Neptune is the eighth planet from the Sun making it the most distant in the solar system. This gas giant planet may have formed much closer to the Sun in early solar system history before migrating to its present position.",
        image: "assets/planets/neptune.png",
        velocity: "5",
        distance: "4428",
        average_orbital_speed: "5.5 km/s",
        satellite: "14",
        surface_area: "7.618 billion km²",
        rotation_period: "0d 16h 6m",
        temperature: "-330°F"),
    PlanetsDesModel(
        name: "Sun",
        position: "9",
        description:"The Sun (or Sol), is the star at the centre of our solar system and is responsible for the Earth’s climate and weather. The Sun is an almost perfect sphere with a difference of just 10km in diameter between the poles and the equator. The average radius of the Sun is 695,508 km (109.2 x that of the Earth) of which 20–25% is the core.",
        image: "assets/planets/sun.png",
        velocity: "220",
        distance: "0",
        average_orbital_speed: "250 km/sec",
        satellite: "0",
        surface_area: "6.09×1012 km2 12,000 × Earth",
        rotation_period: "27 days",
        temperature: "10,000° F"),
  ];
}
